home/urls.py
"""
routing paths for home app
"""
from django.urls import path
from .views import HomeView, InfoView, StaffView, approvereview


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('info/', InfoView.as_view(), name='info'),
    path('staff/', StaffView.as_view(), name='staff'),
    path('approve/<pk>', approvereview, name='approve')

]

hotelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')),
    path('roombook/', include('roombook.urls')),
    path('accounts/', include('allauth.urls')),
    path('reviews/', include('reviews.urls')),
    path('myaccount/', include('myaccount.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
"""
home app views
"""
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.shortcuts import redirect, reverse
from django.core.exceptions import PermissionDenied
from django.views.generic import TemplateView, ListView
from roombook.models import RoomType
from reviews.models import Reviews

# Create your views here.


class HomeView(TemplateView):
    """
    Generic class used to display home page
    get_context_data is overridden to
    include roomtypes and only reviews
    which have been approved
    """
    template_name = "home/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['room_types'] = RoomType.objects.all()
        # only showcase reviews which are featured
        context['reviews'] = Reviews.objects.filter(featured=True)
        return context


class InfoView(TemplateView):
    """
    Generic class used to display information page
    """
    template_name = 'home/info.html'


class StaffView(ListView):
    """
    Generic View used to display staff
    page, queryset is all unapproved
    reviews
    """
    template_name = 'home/staff.html'
    context_object_name = 'reviews'

    def get_queryset(self):
        user = self.request.user
        # check proper user
        if user.is_staff:
            return Reviews.objects.filter(
                approved=False)
        else:
            raise PermissionDenied


def approvereview(request, pk):
    """
    function used to approve reviews
    only available to staff

    Parameters:
    pk: int

    """
    user = request.user
    if user.is_staff:
        booking = get_object_or_404(Reviews, pk=pk)
        booking.approved = True
        booking.save()
        messages.warning(
            request, f'Review number { booking.id } has been approved')
        return redirect(reverse('home:staff'))
    else:
        messages.warning(
            request, 'Reviews may only be approved by staff members')
        return redirect(reverse('home:home'))

templates/home/home.html
{% extends "base.html" %}
{% block title%}Home{% endblock title %}
{% block content%}
<!--==================title======================-->
  <section class="container" style="margin-top:10px;">
      <div class="container " >
          <div class=" text-center title_colour under mb-5 rounded-lg dark">
              <h2 >The Flower Hotel</h2>
              <h3>Choose from our different room sizes. They're all great!  </h3>
          </div>

<!--=====================Room cards========================-->
          <div id = "roomcard" class="row ">
              {% for i in room_types %}
              <div class="col-sm-12  offset-md-3 col-md-6  offset-lg-0 col-lg-4 p-0">
                  <div class=" text-center">
                      <div class="hotel_img">
                          <img class="roompic" src="{{ i.image_url }}" alt="roompicture of an {{i.type}} room">
                          <h4 class="roomtype check1">{{ i.type }}</h4>
                          <h5 class="roomtype check2">€{{ i.price}}/night</h5>
                          <a aria-label="check availability for a {{i.type}} room" href="roombook/book_1/{{i.type}}" class="btn mt-4 check">Check Availability</a>
                      </div>
                      
                  </div>
              
              </div>
              {% endfor %}
          </div>
            <!--===========bootstrap carousel for featured reviews=========-->
          <div id="caro"  class="mb-2  p-2">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="12000">
                <div class="carousel-inner" >
                  
                  {% for review in reviews %}
                    {% if forloop.first %}
                      <div class="carousel-item active">
                        <p class="d-block caro-box w-100 home-review-panel">{{ review.text }}..............{{ review.user.username}}, {{ review.created_on|date}}</p>
                      </div>
                    {% else %}
                      <div class="carousel-item " aria-label="review {{forloop.counter}}">
                        <p class="d-block caro-box w-100 home-review-panel"  >{{ review.text }}..............{{ review.user.username}}, {{ review.created_on|date}}</p>
                      </div>
                    {% endif %}
                  {% empty %}
                      <div class="carousel-item active" aria-label="no reviews yet" >
                        <p class="d-block w-100"  >No Reviews as of now</p>
                      </div>
                  {% endfor %}
                  
                </div>
            </div>
          </div>
            
      </div>
    </section>
        
            

{% endblock %}               

templates/home/info.html
{% extends "base.html" %}
{% block title%}Info{% endblock title %}
{% block content%}
<div>
    
    <!--===================hotel info=================-->
    <article class="container under">
        <div class="container under">
            <h1  class="hotel-title dark  text-center col-sm-12 mt-5 offset-md-3 col-md-6  offset-lg-0 col-lg-4" >The Flower Hotel</h1>
        </div>
        <div class="paratext darker text-center" aria-label="description of the hotel">
            <p>Located in the middle of nowhere, our hotel is perfect for a peaceful stay. The hotel has a private beech and also several ash.
            Our 5 restaurants are all excellant and range in style from casual to 5 star quality fare. Guests can avail of our world famous 
            gardens from which the hotel gets it's name. These gardens were laid out in 1823 by the seventh Vicount of Pantelleria, and still attract
            horticulturalists from around the world especially in Autumn when the tulips are in full bloom.
            </p>
        </div>
    </article>
    <!--blog.duda.com google map -->
    <div class=" container map-responsive mb-2" aria-hidden="true">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d102278.05808585312!2d12.009010603609342!3d36.76602561158638!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x131cabac6626345b%3A0xa7f48b0cc097f78d!2sBalata%20dei%20Turchi!5e0!3m2!1sen!2sie!4v1652302326914!5m2!1sen!2sie" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>



</div>

{% endblock %}

templates/home/staff.html
{% extends "base.html" %}
{% block title%}Staff{% endblock title %}



{% block content%}
    <h1 class="container text-center mt-5">Staff Page</h1>
    <!--list of unapproved reviews awaiting approval===-->
    <div class=" container d-flex flex-column p-1">
        {% for review in reviews %}
            <div class="stafftextbox m-1">
                <div class="mt-1 " ><strong><em>"{{ review.text }}"</em></strong> </div>
                <div class="mt-1">Created by {{ review.user }} on {{ review.created_on }} .</div>
                <div class="text-center p-1 my-1 staffbutton"><a href="{% url 'home:approve' review.id %}">Approve Review</a></div>
            </div>

        {% empty %}
            <div>
                <h1 class="container text-center">No Reviews currently unapproved</h1>
            </div>
        {% endfor %}
    </div>
{% endblock%}