home/urls.py
"""
routing paths for home app
"""
from django.urls import path
from .views import HomeView, InfoView, StaffView, approvereview


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('info/', InfoView.as_view(), name='info'),
    path('staff/', StaffView.as_view(), name='staff'),
    path('approve/<pk>', approvereview, name='approve')

]

hotelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')),
    path('roombook/', include('roombook.urls')),
    path('accounts/', include('allauth.urls')),
    path('reviews/', include('reviews.urls')),
    path('myaccount/', include('myaccount.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myaccount/urls.py
"""
myaccount app url paths
"""
from django.urls import path
from .views import ShowDetails, CancelBooking, ExtendBooking


app_name = 'myaccount'


urlpatterns = [
    path('', ShowDetails.as_view(), name="myaccount"),
    path('cancel/<pk>', CancelBooking.as_view(), name='cancel'),
    path('extend/<pk>', ExtendBooking.as_view(), name='extend'),
]

myaccount/models.py
from django.db import models

# Create your models here.

forms/forms.py
"""
forms used in the application
"""
from django import forms
from roombook.models import Booking


class AvailabilityForm(forms.Form):
    """
    form used in check availability
    """
    check_in = forms.DateField(required=True, widget=forms.DateTimeInput(
                                                    attrs={'type': 'date'}))
    check_out = forms.DateField(required=True, widget=forms.DateTimeInput(
                                                    attrs={'type': 'date'}))

    class Meta:
        fields = ['check_in', 'check_out']


class CancelConfirmForm(forms.Form):
    """
    form used in cancel a booking
    """
    model = Booking

    class Meta:
        fields = ['user', 'room_number', 'check_in', 'check_out']


class ExtendBookingForm(forms.Form):
    """
    form used to extend stay
    """

    new_check_out = forms.DateField(required=True, widget=forms.DateTimeInput(
                            attrs={'type': 'date'}), label=' New Check-Out')

    class Meta:
        fields = ['check_out']

    # oldcheck_out passed in from view with form
    def __init__(self, oldcheck_out, *args, **kwargs):

        # call standard __init__
        super().__init__(*args, **kwargs)
        # make global to make available in clean_new_check_out
        global old_check_out
        old_check_out = oldcheck_out

    def clean_new_check_out(self):
        """
        validate the new check out date
        """
        datum = self.cleaned_data.get('new_check_out')
        print(self.errors.as_data)

        if datum <= old_check_out:
            self.add_error('new_check_out', "dates are wrong")
        return datum

myaccount/views.py
"""
    Myaccount views
"""
from datetime import date
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.shortcuts import redirect, reverse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, View
from roombook.models import Booking
from forms.forms import CancelConfirmForm, ExtendBookingForm
from booking_code.check_extendability import check_extendability


@method_decorator(login_required, name='dispatch')
class ShowDetails(ListView):
    """
        A generic veiw to list all booking of that customer
    """
    template_name = "myaccount/myaccount.html"
    model = Booking
    context_object_name = 'mybookings'

    # override init method to make sure custom model manager is called
    # thus preventing out of date booking being shown on my account page

    def __init__(self, **kwargs):
        Booking.objects.all()
        super().__init__(**kwargs)

    # queryset is all bookings belonging to that customer order by date

    def get_queryset(self):
        return Booking.objects.filter(
            user=self.request.user, is_active=True).order_by('check_in')


@method_decorator(login_required, name='dispatch')
class CancelBooking(SuccessMessageMixin, DeleteView):
    """
     Generic view to delete booking with id of pk.

    """
    # set queryset to one booking selected by user, passed in kwargs
    def get_queryset(self):
        pk = self.kwargs.get('pk', None)
        return Booking.objects.filter(
            pk=pk)

    # add message into delete method
    def delete(self, request, *args, **kwargs):
        bookid = self.kwargs.get('pk', None)
        bookid = get_object_or_404(Booking, pk=bookid)
        # check that the booking is owned by the logged in user
        user = self.request.user
        if bookid.user.username == user.username:
            messages.success(self.request, self.success_message)
            email = request.user.email
            send_mail(
                'Booking Cancelation',
                'Thank you.\nYour booking for the Flower Hotel.\n' +
                'Booking id ' + str(bookid.id) + '\n' +
                'Room Number ' + str(bookid.room_number) + '\n' +
                'Check in ' + str(bookid.check_in) + '\n' +
                'Check Out ' + str(bookid.check_out) + '\n' +
                'Has been canceled',
                'example.com',
                [email],
                fail_silently=False,
            )
            return super(CancelBooking, self).delete(request, *args, **kwargs)
        else:
            messages.warning(request, 'Sorry! This does not appear\
                                to be your booking please contact us for help')
            return redirect(reverse('myaccount:myaccount'))

    model = Booking
    template_name = "myaccount/cancel_booking.html"
    form_class = CancelConfirmForm
    success_url = reverse_lazy("home:home")
    success_message = "The booking has been canceled"

    # overriding get method to check the checkin date is not too close
    def get(self, request, *args, **kwargs):
        user = self.request.user
        bookid = self.kwargs.get('pk', None)
        booking = get_object_or_404(Booking, pk=bookid)
        # checkin to ensure user has the right to view this booking details
        if booking.user.username == user.username:
            today = date.today()
            checkin = booking.check_in
            # if checkin over 7 days away then cancel
            if (checkin - today).days >= 7:
                return render(request, self.template_name, {'booking': booking})
            # if checkin less than 7 days away then deny cancel request
            elif (checkin - today).days < 7:
                messages.warning(request, 'Sorry! Cancelation only\
                    possible if checkin date is more than 7 days away')
                return redirect(reverse('myaccount:myaccount'))
            # if checkin is past tense, deny cancellation request
            elif checkin < today:
                messages.warning(request, 'Sorry! Checkin date has passed')
                return redirect(reverse('myaccount:myaccount'))
            else:
                return redirect(reverse('myaccount:myaccount'))
        else:
            raise PermissionDenied()


@method_decorator(login_required, name='dispatch')
class ExtendBooking(View):
    """
    Class based view to handle stay extension request
    """

    template_name = 'myaccount/extend_booking.html'

    def get(self, request, **kwargs):

        # pass booking data into template
        bookid = self.kwargs.get('pk', None)
        bookid = get_object_or_404(Booking, pk=bookid)

        # pass old check-out date into form for validation
        form = ExtendBookingForm(bookid.check_out)
        context = {
            'bookid': bookid,
            'form': form
        }

        user = self.request.user
        # checking to ensure user has right to view this booking details
        if bookid.user.username == user.username:
            return render(request, self.template_name, context)
        else:
            raise PermissionDenied()

    def post(self, request, **kwargs):
        # pass booking data into template
        bookid = self.kwargs.get('pk', None)
        bookid = get_object_or_404(Booking, pk=bookid)

        user = self.request.user
        # check proper user
        if bookid.user.username == user.username:
            # pass old check-out date into form for validation and form data
            form = ExtendBookingForm(bookid.check_out, request.POST)

            # if new check-out date valid continue else
            #  display error alert and redirect
            if form.is_valid():
                data = form.cleaned_data
            else:
                messages.warning(request, 'Form not valid, New check-out date\
                                             must be after old check-out date')
                return redirect(reverse('myaccount:myaccount'))

            # if particlar room availabile extend booking,
            #  display thank you info and redirect to home
            if check_extendability(
                                    bookid.room_number,
                                    bookid.check_out,
                                    data['new_check_out']):
                bookid.check_out = data['new_check_out']
                bookid.save()
                messages.success(
                                request, f"Thank you for extending room { bookid.room_number } \
                                to { data['new_check_out'] }")
                email = request.user.email
                # confirmation email
                send_mail(
                    'Booking Extended',
                    'Thank you.\nYour booking for the Flower Hotel.\n' +
                    'Booking id ' + str(bookid.id) + '\n' +
                    'Room Number ' + str(bookid.room_number) + '\n' +
                    'Check in ' + str(bookid.check_in) + '\n' +
                    'Has been extended to ' + str(bookid.check_out),
                    'example.com',
                    [email],
                    fail_silently=False,
                )
                return redirect(reverse('home:home'))
            # display alert about room not available and redirect
            else:
                messages.warning(request, "Sorry that room is not available\
                                            for those dates, try another room")
                return redirect(reverse('home:home'))
        else:
            messages.warning(request, 'Sorry! This does not appear to be your\
                                        booking please contact us for help')
            return redirect(reverse('myaccount:myaccount'))

templates/myaccount/cancel_booking.html
{% extends 'base.html' %}
{% block title %}Cancel Booking{% endblock title %}

{% block content %}
<!--===========titles====================================--> 
<h1  class="hotel-title container text-center col-sm-12  offset-md-3 col-md-6 dark offset-lg-0 col-lg-4 topmarlg" >The Flower Hotel</h1>
<h3 class="hotel-title container text-center col-sm-12  offset-md-3 col-md-6 dark offset-lg-0 col-lg-4">Cancel your Booking</h3>
<div class="row justify-content-center m-1 no-gutters">
    <div class="container col-sm-12 mt-5 col-lg-4 offset-lg-4 p-4 review-display " >
<!--==============cancel form============-->
            <form method="post">{% csrf_token %}
     
                <div class=" col-sm-12 col-md-8 offset-md-2 ">
                    <div class="d-flex justify-content-between"><span>Room Number:</span><span>{{ booking.room_number}}</span></div>
                    <div class="d-flex justify-content-between"><span>Check In:</span><span>{{ booking.check_in}}</span></div>
                    <div class="d-flex justify-content-between"><span>Check Out:</span><span>{{ booking.check_out}}</span></div>
                    <div class="text-center m-auto" >
                        <input  class="buttonsty" type="submit" value="Confirm" aria-label="button to cancel booking">
                    </div>
                </div>
            </form>
    </div>
    
</div>       
{% endblock %}

templates/myaccount/extend_booking.html
{% extends 'base.html' %}
{% block title%}Extend Booking{% endblock title %}

{% block content %}
<h1  class="hotel-title container text-center dark col-sm-12  offset-md-3 col-md-6  offset-lg-0 col-lg-4 topmarlg" >The Flower Hotel</h1>
<h3 class="hotel-title container text-center dark col-sm-12  offset-md-3 col-md-6  offset-lg-0 col-lg-4">Extend Your Stay</h3>
<div class="row justify-content-center m-1 m-lg-0 no-gutters">
<div class="container col-sm-12 mt-5 col-lg-4 offset-lg-4 p-4 review-display" >
  
       <!--===================booking details=======-->
        <div class=" col-sm-12 col-md-8 offset-md-2">
            <div class="d-flex justify-content-between"><span style="float:left;">User:</span><span style="float:right;">{{bookid.user}}</span></div>
            <div class="d-flex justify-content-between"><span>Room Number:</span><span>{{ bookid.room_number}}</span></div>
            <div class="d-flex justify-content-between"><span>Check In:</span><span>{{ bookid.check_in}}</span></div>
            <div class="d-flex justify-content-between"><span>Old Check Out:</span><span>{{ bookid.check_out}}</span></div>
            <div  class="mt-3 text-center"><span>Enter new desired check out date</span></div>
            <div>
                <!--==========form for new checkout date====-->
                <form  class="d-flex flex-column text-center" method="POST">
                    {% csrf_token %}
                        <div class="field">
                            <label for="id_new_check_out" class="sr-only">New check out date</label>
                            <div class="control extenddatebox">
                                {{ form.new_check_out}}
                            
                            </div>
                           
                        </div>
                        <div class="text-center m-auto" >
                            <button class ="buttonsty" type="submit" style="display:block;" aria-label="button to extend your stay">Extend </button>
                        </div>
                    
                </form>
            </div>
        
        </div>
    </div>
</div>       
{% endblock %}

templates/myaccount/myaccount.html
{% extends 'base.html' %}
{% block title%}My Account{% endblock title %}

{% block content %}
<div class="container mt-5 bookingtable" style = "padding-left:5px!important; padding-right:5px!important;">
  <div class="col-sm-12  offset-md-2 col-md-8  offset-lg-3 col-lg-6 p-1">
    <div class="row flex-column no-gutters">
        <div>
            <h2 class="text-center dark" >Welcome!</h2>
            <H2 class="text-center dark" > Your Bookings.</H2>
        </div>
        <table class="table koulenfont dark">
          <thead>
            <tr>
              <th scope="col">User</th>
              <th scope="col">Room</th>
              <th scope="col">Check-In</th>
              <th scope="col">Check-Out</th>
              <th scope="col">Extend</th>
              <th scope="col">Cancel</th>
            </tr>
          </thead>
          {% for booking in mybookings %}

          <tbody >
            <tr>
              <th scope="row no-gutters">{{ booking.user }}</th>
              <td>{{ booking.room_number }}</td>
              <td>{{ booking.check_in }}</td>
              <td>{{ booking.check_out }}</td>
              <td> <span><a href="{% url 'myaccount:extend' booking.id %}" aria-label="extend your booking link"><u class="dark">Extend</u></a></span></td>
              <td> <span><a href="{% url 'myaccount:cancel' booking.id %}" aria-label="cancel a booking link"><u class="dark">Cancel</u></a></span></td>
            </tr>
          {% empty %}
            <div>
                <h3 class="text-center">You currently have no bookings</h3>
            </div>
          {% endfor%}  
          </tbody>
        </table>
    </div>
    
    
    
        
  </div>
        <h4  class="text-center dark">User:    {{user.username}}</h4>
        <h4  class="text-center mb-1 dark">User Email:    {{ user.email }}</h4>
        <p class="mb-2"><a href="{% url 'account_change_password' %}" aria-label="change your password"><u class="koulenfont dark">change password</u></a></p>
    </div> 
</div>

{% endblock%}