home/urls.py
"""
routing paths for home app
"""
from django.urls import path
from .views import HomeView, InfoView, StaffView, approvereview


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('info/', InfoView.as_view(), name='info'),
    path('staff/', StaffView.as_view(), name='staff'),
    path('approve/<pk>', approvereview, name='approve')

]

hotelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')),
    path('roombook/', include('roombook.urls')),
    path('accounts/', include('allauth.urls')),
    path('reviews/', include('reviews.urls')),
    path('myaccount/', include('myaccount.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
"""
Url path for reviews app
"""

from django.urls import path
from .views import ReviewView, CreateReview

app_name = 'reviews'

urlpatterns = [
    path('review/', ReviewView.as_view(), name='reviews'),
    path('create_review/', CreateReview.as_view(), name='create_review'),
]

reviews/models.py
"""
Reviews app models
"""
from django.db import models
from django.conf import settings


# Create your models here.
class Reviews(models.Model):
    """
    Reviews app model
    """
    user = models.ForeignKey(
                            settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    text = models.TextField(max_length=300, null=False)
    created_on = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']
        verbose_name_plural = 'Reviews'

    objects = models.Manager()

    def __str__(self):
        return self.user.username

reviews/views.py
"""
Views for review app
"""

from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .models import Reviews


class ReviewView(ListView):
    """
    displays all approved reviews
    paginates on 5 items
    """
    model = Reviews
    template_name = 'reviews/review.html'
    context_object_name = 'hotel_reviews'
    paginate_by = 5

    # display all review which are approved
    def get_queryset(self):
        return Reviews.objects.filter(
            approved=True)


class CreateReview(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Handles the creation of a new review
    uses two mixin classes
    loginrequired and Successmessage
    """
    model = Reviews
    login_url = '/'
    template_name = 'reviews/create_review.html'
    fields = ['text']
    success_url = '/'
    permission_denied_message = 'Please login to leave a review.'
    success_message = 'Thank you for your feedback.\
                             Please allow 24 hours for activation on the site'

    # pre-populate the user field with the current logged in user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    # setup messages for permission denied
    def handle_no_permission(self):
        messages.error(self.request, self.permission_denied_message)
        return super(CreateReview, self).handle_no_permission()

templates/reviews/create_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title%}Create Review{% endblock title %}

{% block content %}
    <section class="container col-sm-12 mt-5 text-center text-white offset-md-3 col-md-6  offset-lg-3 col-lg-6">
        <div class="dark mt-3">
            <h1 class="mt-md-3">The Flower Hotel</h1>
            <h3 class="mt-md-2"> Please Leave your review below</h3>
            <h4 class="mt-md-3"><span>Saving as {{user.username }}</span></h4>
            </div>
        <!--======form for review entry=====-->
        <div class="form-wrapper mt-md-5">
            <form method="post" >
                {% csrf_token %}
                <label for="id_text" class="sr-only">review</label>
                {% for field in form %}
                    {{field}}
                {% endfor %}
                <div style="display:block; margin:auto;"><input class="book-btn" type="submit" value="Submit" aria-label="submit review button"></div>
            </form>
        </div>
       
    </section>
{% endblock %}

templates/reviews/review.html
{% extends 'base.html' %}
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
{% block title%}Reviews{% endblock title %}
{% block content %}
<div class="hotel-title container text-center under dark">
    <div class="">
        <h1>The Flower Hotel</h1>
        <h1  class="mt-3 text-center">Reviews</h1>
    </div>
</div>


<section class="container p-2 text-center" aria-label="list of reviews">
    <!--===========list approved reviews======-->
    {% localtime on %}
    {% for review in hotel_reviews %}
    <div  class="mt-2 mb-1 p-2 review-display">
        <p style="font-size:1.2rem;">{{ review.text }}.......{{review.user.username}}, {{ review.created_on|date }}</p>
    </div>
    {% empty %}
    <div>
        <h1 class="text-white">You have no reviews as of yet</h1>
    </div>
    {% endfor%}
    {% endlocaltime %}

    <div class="pagination justify-content-between">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="dark" href="?page=1" aria-label="first page of reviews">&laquo; first </a>
                <a class="dark" href="?page={{ page_obj.previous_page_number }}" aria-label="previous page of reviews">previous</a>
            {% endif %}
    
            <span class="current ">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a class="darkanchor" href="?page={{ page_obj.next_page_number }}" aria-label="next page of reviews">next</a>
                <a class="darkanchor" href="?page={{ page_obj.paginator.num_pages }}" aria-label="last page of reviews">last &raquo;</a>
            {% endif %}
        </span>
        <span><a class="btn buttonsty" href="{% url 'reviews:create_review' %}"  aria-label="leave a review button">Leave a Review</a></span>
    </div>
</section>
{% endblock %}